name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_KEY: slrk 

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-docker-action@v4
      with:
        context: default
    
    - name: Build the Docker image
      run: |
        export GITHUB_SHA_SHORT="${GITHUB_SHA:0:8}"
        echo "Check GITHUB_SHA_SHORT=${GITHUB_SHA_SHORT}" 
        echo "GITHUB_SHA_SHORT=${GITHUB_SHA_SHORT}" >> $GITHUB_ENV
        docker build . --file Dockerfile --tag my-image-name:${GITHUB_SHA_SHORT}
        echo "Images list..."
        docker image ls

        echo "Docker contexts..."
        docker context ls 

        echo "Changing docker context.."
        docker context use default

        docker image ls

    - name: Run Orca Container Image Scan
      uses: orcasecurity/shiftleft-container-image-action@v1
      with:
        api_token: ${{ secrets.ORCA_SECURITY_API_TOKEN }}
        project_key: slrk
        image: my-image-name:${{ env.GITHUB_SHA_SHORT }}
        debug: true

    - name: Orca CLI - Image Scanning
      env:
        ORCA_SECURITY_API_TOKEN: ${{ secrets.ORCA_SECURITY_API_TOKEN }}
      run: |
        set +e
        apt update && apt install -y curl
        curl -sfL 'https://raw.GitHubusercontent.com/orcasecurity/orca-cli/main/install.sh' | bash
        orca-cli -p "${PROJECT_KEY}" image scan ${IMAGE_NAME}:${GITHUB_SHA_SHORT} 
