name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_KEY: slrk 
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-docker-action@v4
    
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag rk-ci-image:latest
        echo "Images list..."
        docker image ls

        echo "Docker contexts..."
        docker context ls


    - name: Run Orca Container Image Scan
      uses: orcasecurity/shiftleft-container-image-action@v1
      with:
        api_token: ${{ secrets.ORCA_SECURITY_API_TOKEN }}
        project_key: slrk
        image: my-image-name:${{ env.GITHUB_SHA_SHORT }}
        debug: true
